version: 0.0
os: linux

files:
  - source: app.jar
    destination: /home/ec2-user/

hooks:
  ApplicationStop:
    - location: backend/scripts/stop.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: backend/scripts/start.sh
      timeout: 300
      runas: ec2-user