version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: buildright-artifacts-hrushant

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - cd backend
      - mvn clean

  build:
    commands:
      - mvn package -DskipTests

  post_build:
    commands:
      - rm -rf deploy
      - mkdir deploy

      # copy jar
      - cp target/*.jar deploy/app.jar

      # DEBUG: print appspec being copied
      - echo "==== APPSPEC CONTENT ===="
      - cat ../cicd/appspec.yml

      # FORCE overwrite appspec
      - cp -f ../cicd/appspec.yml deploy/appspec.yml

      # copy scripts
      - cp -r ../cicd/scripts deploy/

      # verify inside deploy
      - ls deploy
      - cat deploy/appspec.yml

      # zip
      - cd deploy
      - zip -r app.zip .

      # upload
      - aws s3 cp app.zip s3://$ARTIFACT_BUCKET/app.zip

artifacts:
  files:
    - backend/target/*.jar